// lib/ttsVoices.ts
// Server-only mapping from the app's abstract persona voiceId (generated by
// the Scenario Agent — see lib/schemas.ts's GeneratedScenarioSchema) to a
// real ElevenLabs voice_id. Only ever imported by app/api/speech/route.ts —
// lib/speech.ts is browser-only and never sees an ElevenLabs voice_id or
// API key directly. See CLAUDE.md Hard Invariant #1.
//
// The four literals mirror GeneratedScenarioSchema's voiceId enum by hand
// (same convention as lib/requestSchemas.ts — zod can't reflect over
// another schema's literals at the type level, so keep these in sync if
// that enum changes).
//
// Voice IDs themselves are not hardcoded here: ElevenLabs' voice catalog
// differs per account and plan, so a wrong guess would fail silently at
// the worst possible time (a live meeting). Each persona reads its
// voice_id from its own env var; resolveVoiceId throws if it's unset, and
// the API route treats that the same as a missing ELEVENLABS_API_KEY —
// TTS not configured, fall back to text-only rather than a per-turn error.

export type VoiceId = "af_sarah" | "af_bella" | "am_adam" | "am_michael";

const VOICE_ENV_VARS: Record<VoiceId, string> = {
  af_sarah: "ELEVENLABS_VOICE_AF_SARAH",
  af_bella: "ELEVENLABS_VOICE_AF_BELLA",
  am_adam: "ELEVENLABS_VOICE_AM_ADAM",
  am_michael: "ELEVENLABS_VOICE_AM_MICHAEL",
};

export class VoiceNotConfiguredError extends Error {
  constructor(voiceId: VoiceId, envVar: string) {
    super(`No ElevenLabs voice_id configured for "${voiceId}" — set ${envVar}.`);
    this.name = "VoiceNotConfiguredError";
  }
}

export function resolveVoiceId(voiceId: VoiceId): string {
  const envVar = VOICE_ENV_VARS[voiceId];
  const resolved = process.env[envVar];
  if (!resolved) throw new VoiceNotConfiguredError(voiceId, envVar);
  return resolved;
}
